#!/usr/bin/env bash
# vi: ft=sh
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

JENKINS_IMAGE=jenkins:latest
JENKINS_CONTAINER=jenkins
JENKINS_PORT=11002

docker run --name $JENKINS_CONTAINER -d -p $JENKINS_PORT:8080 -v $PWD/../test-home:/var/jenkins_home -t $JENKINS_IMAGE
